package ivfpq

import (
	"bufio"
	"os"
	"strconv"
	"strings"
	"testing"
)

// loadRef parses testdata/kmeans_ref.txt (one "<name> <fields...>" line per record,
// generated by the roaringrange Rust conformance_ref fixture) into name -> fields.
func loadRef(t *testing.T) map[string][]string {
	t.Helper()
	f, err := os.Open("testdata/kmeans_ref.txt")
	if err != nil {
		t.Fatalf("open reference fixture: %v", err)
	}
	defer f.Close()
	out := map[string][]string{}
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 1<<20), 1<<20)
	for sc.Scan() {
		fields := strings.Fields(sc.Text())
		if len(fields) == 0 {
			continue
		}
		out[fields[0]] = fields[1:]
	}
	if err := sc.Err(); err != nil {
		t.Fatalf("scan reference fixture: %v", err)
	}
	return out
}

// TestRngMatchesRustReference asserts the Go xorshift64* sequence is bit-for-bit
// identical to the Rust trainer's Rng for the same seed.
func TestRngMatchesRustReference(t *testing.T) {
	ref := loadRef(t)
	seed, err := strconv.ParseUint(ref["rng_seed"][0], 16, 64)
	if err != nil {
		t.Fatalf("parse seed: %v", err)
	}
	rng := NewRng(seed)
	for i, want := range ref["rng_seq"] {
		got := rng.NextU64()
		w, err := strconv.ParseUint(want, 16, 64)
		if err != nil {
			t.Fatalf("parse rng_seq[%d]: %v", i, err)
		}
		if got != w {
			t.Fatalf("rng[%d] = %016x, want %016x", i, got, w)
		}
	}
}

// TestNewRngZeroSeed checks a zero seed maps to the golden-ratio constant rather
// than degenerating the generator.
func TestNewRngZeroSeed(t *testing.T) {
	if got := NewRng(0); got.state != rngGoldenRatio {
		t.Errorf("zero seed state = %016x, want %016x", got.state, uint64(rngGoldenRatio))
	}
}
